### ISSUE TITLE
云服务器无法代理问题

### ISSUE THREAD

**Issue by hexl94** [MrLawrenc/Netty_Proxy#1]
本机测试好用，云服务器和本地客户端可以连接，但是代理访问就是不好用，云服务器需要做什么配置吗？9527和要暴露访问的端口都可以ping通

**Comment by MrLawrenc** [comment]
> 本机测试好用，云服务器和本地客户端可以连接，但是代理访问就是不好用，云服务器需要做什么配置吗？9527和要暴露访问的端口都可以ping通

我也用的阿里云，云服务器只要端口打开就可以了，不需要做其他配置，应该是其他问题，需要看下日志。
原来版本有问题，大概运行一两天之后会断，现在这个版本我已经稳定运行近两周了。

**Comment by MrLawrenc** [comment]
> 本机测试好用，云服务器和本地客户端可以连接，但是代理访问就是不好用，云服务器需要做什么配置吗？9527和要暴露访问的端口都可以ping通

或者你可以把日志邮件发给我 mrliu943903861@163.com

**Comment by hexl94** [comment]
找到问题了，我是用docker部署就会有这个问题，直接部署就不会有问题。
请问下docker部署怎么解决

**Comment by MrLawrenc** [comment]
> 找到问题了，我是用docker部署就会有这个问题，直接部署就不会有问题。
> 请问下docker部署怎么解决

请确保docker开启了端口映射（如 -p 3306:3306）  否则容器外通过代理端口是访问不到docker容器内的代理应用的
