### ISSUE TITLE
运行一段时间还是会自己关闭

### ISSUE THREAD

**Issue by hexl94** [MrLawrenc/Netty_Proxy#2]
运行一段时间还是会自己关闭，两周以后服务端还是自己关闭了

**Comment by MrLawrenc** [comment]
之前代码改动了忘记打release了，尝试更新到最新吧，我用最新的稳定一个月了
 
![image](https://user-images.githubusercontent.com/35510822/83409744-981ea580-a447-11ea-8808-881d4cabbec3.png)

**Comment by MrLawrenc** [comment]
> 运行一段时间还是会自己关闭，两周以后服务端还是自己关闭了

**Comment by MrLawrenc** [comment]
> 运行一段时间还是会自己关闭，两周以后服务端还是自己关闭了

之前代码改动了忘记打release了，尝试更新到最新吧，我用最新的稳定一个月了
![tempsnip](https://user-images.githubusercontent.com/35510822/83409924-fb103c80-a447-11ea-96ec-cc6d37a1aab1.png)
