### ISSUE TITLE
博文 Netty内网穿透原理

### ISSUE THREAD

**Issue by leafgrey** [MrLawrenc/Netty_Proxy#5]
https://lmy25.wang/archives/Netty%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F%E5%8E%9F%E7%90%86

老板  这个博文没有了吗

**Comment by MrLawrenc** [comment]
> https://lmy25.wang/archives/Netty%E5%86%85%E7%BD%91%E7%A9%BF%E9%80%8F%E5%8E%9F%E7%90%86
> 
> 老板 这个博文没有了吗

有的吧  个人站数据全是存在内网笔记本上的  服务器又是阿里云1m带宽的（还挂了其他服务） 所以有时候访问比较慢 后面考虑优化优化

**Comment by leafgrey** [comment]
没了 怎么打开都是 500err  网站有bug？:)

**Comment by MrLawrenc** [comment]
> 没了 怎么打开都是 500err 网站有bug？:)

没bug。。。太多东西了就是单纯卡  哈哈 自己记点东西用的    开源halo搭建的 [halo](https://github.com/halo-dev/halo)

**Comment by emmdu** [comment]
想看博文
